import { Category, Product } from "@/types/pos";

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, name: "BATUTS", sort_order: 1, color: "#8B5CF6" },
  { id: 2, name: "BEGUDES", sort_order: 2, color: "#3B82F6" },
  { id: 3, name: "BERLINES", sort_order: 3, color: "#FB923C" },
  { id: 4, name: "CAFES", sort_order: 4, color: "#92400E" },
  { id: 5, name: "ESPECIALITATS", sort_order: 5, color: "#D946EF" },
  { id: 6, name: "CREPES", sort_order: 6, color: "#EAB308" },
  { id: 7, name: "DOUGHT", sort_order: 7, color: "#F97316" },
  { id: 8, name: "FRAPPES", sort_order: 8, color: "#78350F" },
  { id: 9, name: "GELATS", sort_order: 9, color: "#EC4899" },
  { id: 10, name: "GRANISSATS", sort_order: 10, color: "#34D399" },
  { id: 11, name: "HI POP", sort_order: 11, color: "#F59E0B" },
  { id: 12, name: "ICE DRINKS", sort_order: 12, color: "#06B6D4" },
  { id: 13, name: "RECEPTES", sort_order: 13, color: "#F43F5E" },
  { id: 14, name: "SMOOTHIE", sort_order: 14, color: "#10B981" },
  { id: 15, name: "FROZZEN IOGURT", sort_order: 15, color: "#E879F9" },
  { id: 16, name: "XIPS", sort_order: 16, color: "#84CC16" },
  { id: 17, name: "XURROS", sort_order: 17, color: "#F97316" },
  { id: 18, name: "VARIOS", sort_order: 18, color: "#6B7280" },
  { id: 19, name: "SABORS", sort_order: 19, color: "#A78BFA" },
  { id: 20, name: "SALSAS I CREMES", sort_order: 20, color: "#FDA4AF" },
  { id: 21, name: "TOPPINGS", sort_order: 21, color: "#FBBF24" },
  { id: 22, name: "TOPPING GELAT 1\u20AC", sort_order: 22, color: "#60A5FA" },
  { id: 23, name: "TOPPING 1\u20AC EXTRA", sort_order: 23, color: "#F472B6" },
  { id: 24, name: "TOPPING GELAT 2\u20AC", sort_order: 24, color: "#2DD4BF" },
  { id: 25, name: "TOPPINGS 0,5\u20AC", sort_order: 25, color: "#A855F7" },
  { id: 26, name: "INFUSIONS", sort_order: 26, color: "#65A30D" },
  { id: 27, name: "ORXATA", sort_order: 27, color: "#FCA5A5" },
];

export const MOCK_PRODUCTS: Product[] = [
  // ── BATUTS (cat 1) — all 5.90€ ──
  { id: 1, name: "BATUT GELAT", category_id: 1, price: 5.90, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "BATUTS", category_color: "#8B5CF6" },
  { id: 2, name: "BATUT VAINILLA", category_id: 1, price: 5.90, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "BATUTS", category_color: "#8B5CF6" },
  { id: 3, name: "BATUT XOCOLATA", category_id: 1, price: 5.90, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "BATUTS", category_color: "#8B5CF6" },
  { id: 4, name: "BATUT MADUIXA", category_id: 1, price: 5.90, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "BATUTS", category_color: "#8B5CF6" },
  { id: 5, name: "BATUT MANGO", category_id: 1, price: 5.90, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "BATUTS", category_color: "#8B5CF6" },

  // ── BEGUDES (cat 2) ──
  { id: 6, name: "7UP", category_id: 2, price: 2.50, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 7, name: "AIGUA 1,5", category_id: 2, price: 3.95, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 8, name: "AIGUA AMB GAS", category_id: 2, price: 2.50, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 9, name: "AIGUA 50 CC", category_id: 2, price: 1.95, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 10, name: "AQUARIUS LLIMONA", category_id: 2, price: 2.95, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 11, name: "BEGUDES VEINS", category_id: 2, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 12, name: "BITTER KAS", category_id: 2, price: 2.95, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 13, name: "CACAOLAT", category_id: 2, price: 2.95, vat_rate: 10, image_url: null, active: true, sort_order: 8, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 14, name: "COKE", category_id: 2, price: 2.50, vat_rate: 10, image_url: null, active: true, sort_order: 9, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 15, name: "COKE 00", category_id: 2, price: 2.50, vat_rate: 10, image_url: null, active: true, sort_order: 10, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 16, name: "DAMM LEMON", category_id: 2, price: 2.50, vat_rate: 10, image_url: null, active: true, sort_order: 11, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 17, name: "ESTRELLA", category_id: 2, price: 2.50, vat_rate: 10, image_url: null, active: true, sort_order: 12, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 18, name: "FANTA LLIMONA", category_id: 2, price: 2.50, vat_rate: 10, image_url: null, active: true, sort_order: 13, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 19, name: "FANTA TARONJA", category_id: 2, price: 2.50, vat_rate: 10, image_url: null, active: true, sort_order: 14, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 20, name: "FREE DAMM", category_id: 2, price: 2.50, vat_rate: 10, image_url: null, active: true, sort_order: 15, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 21, name: "GRANINI PI\u00D1A", category_id: 2, price: 2.95, vat_rate: 10, image_url: null, active: true, sort_order: 16, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 22, name: "GRANINI PR\u00C9SSEC", category_id: 2, price: 2.95, vat_rate: 10, image_url: null, active: true, sort_order: 17, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 23, name: "GRANINI TARONJA", category_id: 2, price: 2.95, vat_rate: 10, image_url: null, active: true, sort_order: 18, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 24, name: "NESTEA", category_id: 2, price: 2.95, vat_rate: 10, image_url: null, active: true, sort_order: 19, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 25, name: "FREE DAMM TORRADA", category_id: 2, price: 2.50, vat_rate: 10, image_url: null, active: true, sort_order: 20, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 26, name: "TONICA SWEPPES", category_id: 2, price: 2.95, vat_rate: 10, image_url: null, active: true, sort_order: 21, category_name: "BEGUDES", category_color: "#3B82F6" },
  { id: 27, name: "CASA HI CREAM", category_id: 2, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 22, category_name: "BEGUDES", category_color: "#3B82F6" },

  // ── BERLINES (cat 3) ──
  { id: 28, name: "MAX KINDER", category_id: 3, price: 3.95, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "BERLINES", category_color: "#FB923C" },
  { id: 29, name: "MAX LOTUS", category_id: 3, price: 3.95, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "BERLINES", category_color: "#FB923C" },
  { id: 30, name: "MAX OREO", category_id: 3, price: 3.95, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "BERLINES", category_color: "#FB923C" },
  { id: 31, name: "MAX PISTACHO", category_id: 3, price: 3.95, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "BERLINES", category_color: "#FB923C" },
  { id: 32, name: "MINI DONUT DECORAT", category_id: 3, price: 1.50, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "BERLINES", category_color: "#FB923C" },
  { id: 33, name: "BERLINES HOT HELADO", category_id: 3, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "BERLINES", category_color: "#FB923C" },
  { id: 34, name: "MINI DONUT", category_id: 3, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "BERLINES", category_color: "#FB923C" },

  // ── CAFES (cat 4) ──
  { id: 35, name: "CAFE AMB LLET", category_id: 4, price: 2.25, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "CAFES", category_color: "#92400E" },
  { id: 36, name: "CAFE AMB LLET DESCAFE\u00CFNAT", category_id: 4, price: 2.25, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "CAFES", category_color: "#92400E" },
  { id: 37, name: "CAFE I GELAT", category_id: 4, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "CAFES", category_color: "#92400E" },
  { id: 38, name: "CAFE VE\u00CFNS", category_id: 4, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "CAFES", category_color: "#92400E" },
  { id: 39, name: "CAF\u00C8", category_id: 4, price: 1.95, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "CAFES", category_color: "#92400E" },
  { id: 40, name: "CAF\u00C8 AMERIC\u00C0", category_id: 4, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "CAFES", category_color: "#92400E" },
  { id: 41, name: "CAF\u00C9 DESCAFEINAT", category_id: 4, price: 1.95, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "CAFES", category_color: "#92400E" },
  { id: 42, name: "CAPUCCINO", category_id: 4, price: 2.75, vat_rate: 10, image_url: null, active: true, sort_order: 8, category_name: "CAFES", category_color: "#92400E" },
  { id: 43, name: "CAPUCCINO DESCAFEINAT", category_id: 4, price: 2.75, vat_rate: 10, image_url: null, active: true, sort_order: 9, category_name: "CAFES", category_color: "#92400E" },
  { id: 44, name: "DOBLE EXPRESSO", category_id: 4, price: 3.25, vat_rate: 10, image_url: null, active: true, sort_order: 10, category_name: "CAFES", category_color: "#92400E" },
  { id: 45, name: "TALLAT", category_id: 4, price: 2.10, vat_rate: 10, image_url: null, active: true, sort_order: 11, category_name: "CAFES", category_color: "#92400E" },
  { id: 46, name: "TALLAT DESCAFE\u00CDNAT", category_id: 4, price: 2.10, vat_rate: 10, image_url: null, active: true, sort_order: 12, category_name: "CAFES", category_color: "#92400E" },
  { id: 47, name: "XOCOLATA A LA TASSA", category_id: 4, price: 3.50, vat_rate: 10, image_url: null, active: true, sort_order: 13, category_name: "CAFES", category_color: "#92400E" },
  { id: 48, name: "CAFE CASA", category_id: 4, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 14, category_name: "CAFES", category_color: "#92400E" },
  { id: 49, name: "COLA CAO", category_id: 4, price: 2.50, vat_rate: 10, image_url: null, active: true, sort_order: 15, category_name: "CAFES", category_color: "#92400E" },
  { id: 50, name: "BOMBO", category_id: 4, price: 2.25, vat_rate: 10, image_url: null, active: true, sort_order: 16, category_name: "CAFES", category_color: "#92400E" },

  // ── ESPECIALITATS (cat 5) ──
  { id: 51, name: "MATCHA LATE", category_id: 5, price: 3.95, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "ESPECIALITATS", category_color: "#D946EF" },
  { id: 52, name: "PISTACHO LATTE", category_id: 5, price: 4.20, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "ESPECIALITATS", category_color: "#D946EF" },
  { id: 53, name: "CHAI LATE", category_id: 5, price: 3.95, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "ESPECIALITATS", category_color: "#D946EF" },
  { id: 54, name: "MATCHA MADUIXA", category_id: 5, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "ESPECIALITATS", category_color: "#D946EF" },
  { id: 55, name: "MATCHA MANGO", category_id: 5, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "ESPECIALITATS", category_color: "#D946EF" },
  { id: 56, name: "MATCHA COCO", category_id: 5, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "ESPECIALITATS", category_color: "#D946EF" },
  { id: 57, name: "CHAI PISTATXO", category_id: 5, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "ESPECIALITATS", category_color: "#D946EF" },
  { id: 58, name: "CHAI XOCOLATA NEGRE", category_id: 5, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 8, category_name: "ESPECIALITATS", category_color: "#D946EF" },
  { id: 59, name: "SPECIAL VAINILLA", category_id: 5, price: 4.40, vat_rate: 10, image_url: null, active: true, sort_order: 9, category_name: "ESPECIALITATS", category_color: "#D946EF" },
  { id: 60, name: "SPECIAL CARAMEL", category_id: 5, price: 4.40, vat_rate: 10, image_url: null, active: true, sort_order: 10, category_name: "ESPECIALITATS", category_color: "#D946EF" },
  { id: 61, name: "SPECIAL AVELLANA", category_id: 5, price: 4.40, vat_rate: 10, image_url: null, active: true, sort_order: 11, category_name: "ESPECIALITATS", category_color: "#D946EF" },
  { id: 62, name: "SPECIAL MOCHA BLANC", category_id: 5, price: 4.40, vat_rate: 10, image_url: null, active: true, sort_order: 12, category_name: "ESPECIALITATS", category_color: "#D946EF" },
  { id: 63, name: "SPECIAL MOCHA NEGRE", category_id: 5, price: 4.40, vat_rate: 10, image_url: null, active: true, sort_order: 13, category_name: "ESPECIALITATS", category_color: "#D946EF" },
  { id: 64, name: "SPECIAL LOTUS", category_id: 5, price: 4.40, vat_rate: 10, image_url: null, active: true, sort_order: 14, category_name: "ESPECIALITATS", category_color: "#D946EF" },

  // ── CREPES (cat 6) ──
  { id: 65, name: "CREPE", category_id: 6, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "CREPES", category_color: "#EAB308" },
  { id: 66, name: "MEDITERRANEO", category_id: 6, price: 6.90, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "CREPES", category_color: "#EAB308" },
  { id: 67, name: "MIXTO", category_id: 6, price: 6.90, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "CREPES", category_color: "#EAB308" },
  { id: 68, name: "QUESOS", category_id: 6, price: 7.50, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "CREPES", category_color: "#EAB308" },
  { id: 69, name: "CREPE NUTELLA", category_id: 6, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "CREPES", category_color: "#EAB308" },
  { id: 70, name: "CREPE PISTATXO", category_id: 6, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "CREPES", category_color: "#EAB308" },
  { id: 71, name: "CREPE KINDER", category_id: 6, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "CREPES", category_color: "#EAB308" },
  { id: 72, name: "CREPE XOCOLATA", category_id: 6, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 8, category_name: "CREPES", category_color: "#EAB308" },
  { id: 73, name: "CREPE XOCOLATA BLANCA", category_id: 6, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 9, category_name: "CREPES", category_color: "#EAB308" },
  { id: 74, name: "CREPE SALSA OREO", category_id: 6, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 10, category_name: "CREPES", category_color: "#EAB308" },
  { id: 286, name: "CREPE DE LA CASA", category_id: 6, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 11, category_name: "CREPES", category_color: "#EAB308" },

  // ── DOUGHT (cat 7) ──
  { id: 75, name: "DOGHT BOX 6 UD.", category_id: 7, price: 7.50, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "DOUGHT", category_color: "#F97316" },
  { id: 76, name: "DOGHT BOX 9 UD.", category_id: 7, price: 9.90, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "DOUGHT", category_color: "#F97316" },
  { id: 284, name: "DOGHT BOX 12 UD.", category_id: 7, price: 11.90, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "DOUGHT", category_color: "#F97316" },
  { id: 285, name: "DOGHT BOX 16 UD.", category_id: 7, price: 14.90, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "DOUGHT", category_color: "#F97316" },

  // ── FRAPPES (cat 8) ──
  { id: 77, name: "FRAPPE CLASIC", category_id: 8, price: 5.95, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "FRAPPES", category_color: "#78350F" },
  { id: 78, name: "FRAPPE & NATA", category_id: 8, price: 6.90, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "FRAPPES", category_color: "#78350F" },
  { id: 79, name: "FRAPPE MATCHA", category_id: 8, price: 6.90, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "FRAPPES", category_color: "#78350F" },
  { id: 80, name: "FRAPUCCINO CANDY", category_id: 8, price: 6.90, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "FRAPPES", category_color: "#78350F" },
  { id: 81, name: "FRAPUCCINO VAINILLA", category_id: 8, price: 6.90, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "FRAPPES", category_color: "#78350F" },
  { id: 82, name: "FRAPPE PISTATXO", category_id: 8, price: 6.90, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "FRAPPES", category_color: "#78350F" },

  // ── GELATS (cat 9) ──
  { id: 83, name: "CUCURUTXO L", category_id: 9, price: 6.50, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "GELATS", category_color: "#EC4899" },
  { id: 84, name: "CUCURUTXO M", category_id: 9, price: 4.85, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "GELATS", category_color: "#EC4899" },
  { id: 85, name: "CUCURUTXO S", category_id: 9, price: 3.95, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "GELATS", category_color: "#EC4899" },
  { id: 86, name: "POT L", category_id: 9, price: 6.50, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "GELATS", category_color: "#EC4899" },
  { id: 87, name: "POT M", category_id: 9, price: 4.85, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "GELATS", category_color: "#EC4899" },
  { id: 88, name: "POT S", category_id: 9, price: 3.95, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "GELATS", category_color: "#EC4899" },
  { id: 89, name: "TUPPER", category_id: 9, price: 9.95, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "GELATS", category_color: "#EC4899" },

  // ── GRANISSATS (cat 10) — all 4.90€ ──
  { id: 90, name: "GRANITZAT COCO", category_id: 10, price: 4.90, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "GRANISSATS", category_color: "#34D399" },
  { id: 91, name: "GRANITZAT FRAMBUESA", category_id: 10, price: 4.90, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "GRANISSATS", category_color: "#34D399" },
  { id: 92, name: "GRANITZAT LLIMONA", category_id: 10, price: 4.90, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "GRANISSATS", category_color: "#34D399" },
  { id: 93, name: "GRANITZAT MADUIXA", category_id: 10, price: 4.90, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "GRANISSATS", category_color: "#34D399" },
  { id: 94, name: "GRANITZAT MANGO", category_id: 10, price: 4.90, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "GRANISSATS", category_color: "#34D399" },
  { id: 287, name: "GRANITZAT IOGURT", category_id: 10, price: 4.90, vat_rate: 10, image_url: null, active: true, sort_order: 11, category_name: "GRANISSATS", category_color: "#34D399" },

  // ── HI POP (cat 11) ──
  { id: 95, name: "AMERICAN WAFFLE", category_id: 11, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "HI POP", category_color: "#F59E0B" },
  { id: 96, name: "SANDWICH WAFFLE", category_id: 11, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "HI POP", category_color: "#F59E0B" },
  { id: 97, name: "HI POP", category_id: 11, price: 6.90, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "HI POP", category_color: "#F59E0B" },
  { id: 98, name: "WAFFLE NUTELLA", category_id: 11, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "HI POP", category_color: "#F59E0B" },
  { id: 99, name: "SANDWIC KINDER", category_id: 11, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "HI POP", category_color: "#F59E0B" },
  { id: 100, name: "WAFFLE KINDER", category_id: 11, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "HI POP", category_color: "#F59E0B" },
  { id: 101, name: "WAFFLE PISTATXO", category_id: 11, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "HI POP", category_color: "#F59E0B" },
  { id: 102, name: "WAFFLE XOCOLATA", category_id: 11, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 8, category_name: "HI POP", category_color: "#F59E0B" },
  { id: 103, name: "WAFFLE XOCOLATA BLANCA", category_id: 11, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 9, category_name: "HI POP", category_color: "#F59E0B" },
  { id: 104, name: "SANDWICH NUTELLA", category_id: 11, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 10, category_name: "HI POP", category_color: "#F59E0B" },
  { id: 105, name: "SANDWICH PISTATXO", category_id: 11, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 11, category_name: "HI POP", category_color: "#F59E0B" },
  { id: 106, name: "SANDWICH XOCOLATA", category_id: 11, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 12, category_name: "HI POP", category_color: "#F59E0B" },
  { id: 107, name: "SANDWICH XOCOLATA BLANCA", category_id: 11, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 13, category_name: "HI POP", category_color: "#F59E0B" },
  { id: 108, name: "SANDWICH SALSA OREO", category_id: 11, price: 4.95, vat_rate: 10, image_url: null, active: true, sort_order: 14, category_name: "HI POP", category_color: "#F59E0B" },

  // ── ICE DRINKS (cat 12) — all 4.90€ ──
  { id: 109, name: "ICED MADUIXA", category_id: 12, price: 4.90, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "ICE DRINKS", category_color: "#06B6D4" },
  { id: 110, name: "ICED CAFE", category_id: 12, price: 4.90, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "ICE DRINKS", category_color: "#06B6D4" },
  { id: 111, name: "ICED MANGO", category_id: 12, price: 4.90, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "ICE DRINKS", category_color: "#06B6D4" },
  { id: 112, name: "ICED LLIMONA", category_id: 12, price: 4.90, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "ICE DRINKS", category_color: "#06B6D4" },
  { id: 113, name: "ICED MARACUIA", category_id: 12, price: 4.90, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "ICE DRINKS", category_color: "#06B6D4" },
  { id: 114, name: "MILK CAFE", category_id: 12, price: 4.90, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "ICE DRINKS", category_color: "#06B6D4" },
  { id: 115, name: "MILK MANGO", category_id: 12, price: 4.90, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "ICE DRINKS", category_color: "#06B6D4" },
  { id: 116, name: "MILK MARACUIA", category_id: 12, price: 4.90, vat_rate: 10, image_url: null, active: true, sort_order: 8, category_name: "ICE DRINKS", category_color: "#06B6D4" },

  // ── RECEPTES (cat 13) — all 7.30€ ──
  { id: 117, name: "COOKIES CREAM", category_id: 13, price: 7.30, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "RECEPTES", category_color: "#F43F5E" },
  { id: 118, name: "KINDER DELIGHT", category_id: 13, price: 7.30, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "RECEPTES", category_color: "#F43F5E" },
  { id: 119, name: "LOTUS RECETA", category_id: 13, price: 7.30, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "RECEPTES", category_color: "#F43F5E" },
  { id: 120, name: "NUTELLA & GO", category_id: 13, price: 7.30, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "RECEPTES", category_color: "#F43F5E" },
  { id: 121, name: "OREO ICE", category_id: 13, price: 7.30, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "RECEPTES", category_color: "#F43F5E" },
  { id: 122, name: "PISTACHO RECETA", category_id: 13, price: 7.30, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "RECEPTES", category_color: "#F43F5E" },
  { id: 123, name: "T\u00C9 MACHA RECETA", category_id: 13, price: 7.30, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "RECEPTES", category_color: "#F43F5E" },
  { id: 124, name: "YOGURT PASI\u00D3N", category_id: 13, price: 7.30, vat_rate: 10, image_url: null, active: true, sort_order: 8, category_name: "RECEPTES", category_color: "#F43F5E" },
  { id: 280, name: "CHAI", category_id: 13, price: 7.30, vat_rate: 10, image_url: null, active: true, sort_order: 9, category_name: "RECEPTES", category_color: "#F43F5E" },

  // ── SMOOTHIE (cat 14) — all 5.90€ ──
  { id: 125, name: "SMOOTHIE COCO", category_id: 14, price: 5.90, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "SMOOTHIE", category_color: "#10B981" },
  { id: 126, name: "SMOOTHIE FRAMBUESA", category_id: 14, price: 5.90, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "SMOOTHIE", category_color: "#10B981" },
  { id: 127, name: "SMOOTHIE FRESA", category_id: 14, price: 5.90, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "SMOOTHIE", category_color: "#10B981" },
  { id: 128, name: "SMOOTHIE MANGO", category_id: 14, price: 5.90, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "SMOOTHIE", category_color: "#10B981" },
  { id: 129, name: "SMOOTHIE MARACUYA", category_id: 14, price: 5.90, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "SMOOTHIE", category_color: "#10B981" },
  { id: 130, name: "SMOOTHIE A\u00C7AI", category_id: 14, price: 5.90, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "SMOOTHIE", category_color: "#10B981" },

  // ── FROZZEN IOGURT (cat 15) ──
  { id: 131, name: "POT IOGURT L", category_id: 15, price: 5.95, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "FROZZEN IOGURT", category_color: "#E879F9" },
  { id: 132, name: "POT IOGURT M", category_id: 15, price: 4.75, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "FROZZEN IOGURT", category_color: "#E879F9" },
  { id: 133, name: "POT IOGURT S", category_id: 15, price: 3.60, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "FROZZEN IOGURT", category_color: "#E879F9" },
  { id: 134, name: "A\u00C7AI L", category_id: 15, price: 5.95, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "FROZZEN IOGURT", category_color: "#E879F9" },
  { id: 135, name: "A\u00C7AI M", category_id: 15, price: 4.75, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "FROZZEN IOGURT", category_color: "#E879F9" },
  { id: 136, name: "A\u00C7AI S", category_id: 15, price: 3.60, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "FROZZEN IOGURT", category_color: "#E879F9" },
  { id: 137, name: "A\u00C7AI S MUESLY", category_id: 15, price: 3.60, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "FROZZEN IOGURT", category_color: "#E879F9" },

  // ── XIPS (cat 16) ──
  { id: 138, name: "PATATES XIPS", category_id: 16, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "XIPS", category_color: "#84CC16" },

  // ── XURROS (cat 17) ──
  { id: 139, name: "BOX 6 XURROS + 2 XOCOLATA", category_id: 17, price: 9.90, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "XURROS", category_color: "#F97316" },
  { id: 140, name: "BOX 9 XURROS + 3 XOCOLATA", category_id: 17, price: 14.90, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "XURROS", category_color: "#F97316" },
  { id: 141, name: "PACK 3 XURROS SUCRE", category_id: 17, price: 3.30, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "XURROS", category_color: "#F97316" },
  { id: 142, name: "PACK 3 XURROS XOCOLATA", category_id: 17, price: 5.30, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "XURROS", category_color: "#F97316" },
  { id: 143, name: "XOCOLATA & XURROS", category_id: 17, price: 5.90, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "XURROS", category_color: "#F97316" },
  { id: 144, name: "XURRO XOCOLATA", category_id: 17, price: 1.90, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "XURROS", category_color: "#F97316" },
  { id: 145, name: "XURRO MADUIXA", category_id: 17, price: 1.90, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "XURROS", category_color: "#F97316" },
  { id: 146, name: "PACK 3 XURROS PISTATXO", category_id: 17, price: 5.30, vat_rate: 10, image_url: null, active: true, sort_order: 8, category_name: "XURROS", category_color: "#F97316" },
  { id: 147, name: "PACK 3 XURROS", category_id: 17, price: 5.30, vat_rate: 10, image_url: null, active: true, sort_order: 9, category_name: "XURROS", category_color: "#F97316" },
  { id: 148, name: "MADUIXA", category_id: 17, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 10, category_name: "XURROS", category_color: "#F97316" },
  { id: 149, name: "PACK 3 XURROS XOCO B", category_id: 17, price: 5.90, vat_rate: 10, image_url: null, active: true, sort_order: 11, category_name: "XURROS", category_color: "#F97316" },

  // ── VARIOS (cat 18) ──
  { id: 150, name: "GEL", category_id: 18, price: 0.10, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "VARIOS", category_color: "#6B7280" },
  { id: 151, name: "SUPLEMENT LLET VEGETAL", category_id: 18, price: 0.30, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "VARIOS", category_color: "#6B7280" },
  { id: 152, name: "VARIOS", category_id: 18, price: 1.30, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "VARIOS", category_color: "#6B7280" },
  { id: 153, name: "DESCAFEINAT SOBRE", category_id: 18, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "VARIOS", category_color: "#6B7280" },
  { id: 154, name: "SENSE SUCRE", category_id: 18, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "VARIOS", category_color: "#6B7280" },
  { id: 155, name: "SUCRE MORE", category_id: 18, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "VARIOS", category_color: "#6B7280" },
  { id: 156, name: "LLET SENSE LACTOSA", category_id: 18, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "VARIOS", category_color: "#6B7280" },
  { id: 157, name: "LLET VEGETAL 0\u20AC", category_id: 18, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 8, category_name: "VARIOS", category_color: "#6B7280" },
  { id: 291, name: "IMPORTE LIBRE", category_id: 18, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 99, category_name: "VARIOS", category_color: "#6B7280" },

  // ── SABORS (cat 19) — all 0.00€ ──
  { id: 158, name: "SABOR AVELLANA", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 159, name: "SABOR CAFE", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 160, name: "SABOR CHEESECAKE", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 161, name: "SABOR COCO", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 162, name: "SABOR DOL\u00C7 DE LLET", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 163, name: "SABOR FERRERO", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 164, name: "SABOR KINDER", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 165, name: "SABOR LLIMONA", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 8, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 166, name: "SABOR LOTUS", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 9, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 167, name: "SABOR MADUIXA", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 10, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 168, name: "SABOR MANGO", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 11, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 169, name: "SABOR MARACUIA", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 12, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 170, name: "SABOR MENTA XOCO", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 13, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 171, name: "SABOR NATA", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 14, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 172, name: "SABOR NUTELLA", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 15, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 173, name: "SABOR OREO", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 16, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 174, name: "SABOR PISTAXO", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 17, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 175, name: "SABOR TURRO", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 18, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 176, name: "SABOR VAINILLA", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 19, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 177, name: "SABOR VAINILLA COOKIES", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 20, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 178, name: "SABOR XOCOLATA", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 21, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 179, name: "SABOR STRACCIATELLA", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 22, category_name: "SABORS", category_color: "#A78BFA" },
  { id: 180, name: "SABOR CRISPETES", category_id: 19, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 23, category_name: "SABORS", category_color: "#A78BFA" },

  // ── SALSAS I CREMES (cat 20) ──
  { id: 181, name: "XOCOLATA", category_id: 20, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 182, name: "XOCOLATA BLANCA", category_id: 20, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 183, name: "PISTATXO SALSA", category_id: 20, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 184, name: "DOL\u00C7 DE LLET", category_id: 20, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 185, name: "KINDER SALSA", category_id: 20, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 186, name: "LOTUS SALSA", category_id: 20, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 187, name: "MELMELADA NABIUS", category_id: 20, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 188, name: "OREO SALSA", category_id: 20, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 8, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 189, name: "XOCO MADUIXA", category_id: 20, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 9, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 190, name: "MELMALADA MARACUIA", category_id: 20, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 10, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 191, name: "CARAMEL SALAT", category_id: 20, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 11, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 192, name: "MELMALADA FRUITS VERMELLS", category_id: 20, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 12, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 193, name: "XOCOLATA PISTATXO", category_id: 20, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 13, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 194, name: "CREMA CATALANA 1\u20AC", category_id: 20, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 14, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 195, name: "KINDER SALSA 1\u20AC", category_id: 20, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 15, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 196, name: "LOTUS SALSA 1\u20AC", category_id: 20, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 16, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 197, name: "PISTAXO SALSA 1\u20AC", category_id: 20, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 17, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 198, name: "XOCOLATA BLANCA 1\u20AC", category_id: 20, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 18, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 199, name: "CARAMEL SALAT 1\u20AC", category_id: 20, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 19, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 200, name: "DOL\u00C7 DE LLET 0.50\u20AC", category_id: 20, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 20, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 201, name: "KINDER SALSA 0.5\u20AC", category_id: 20, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 21, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 202, name: "LOTUS SALSA 0.5\u20AC", category_id: 20, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 22, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 203, name: "PISTAXO SALSA 0.5\u20AC", category_id: 20, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 23, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 204, name: "XOCOLATA 0.5\u20AC", category_id: 20, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 24, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },
  { id: 205, name: "XOCOLATA BLANCA 0.5\u20AC", category_id: 20, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 25, category_name: "SALSAS I CREMES", category_color: "#FDA4AF" },

  // ── TOPPINGS (cat 21) — all 0.00€ ──
  { id: 206, name: "NUTELLA", category_id: 21, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "TOPPINGS", category_color: "#FBBF24" },
  { id: 207, name: "CRISPY BALLS BLANCA", category_id: 21, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "TOPPINGS", category_color: "#FBBF24" },
  { id: 208, name: "LACASITOS", category_id: 21, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "TOPPINGS", category_color: "#FBBF24" },
  { id: 209, name: "LOTUS POLS", category_id: 21, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "TOPPINGS", category_color: "#FBBF24" },
  { id: 210, name: "MADUIXA NATURAL", category_id: 21, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "TOPPINGS", category_color: "#FBBF24" },
  { id: 211, name: "NATA", category_id: 21, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "TOPPINGS", category_color: "#FBBF24" },
  { id: 212, name: "NUBE", category_id: 21, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "TOPPINGS", category_color: "#FBBF24" },
  { id: 213, name: "OREO POLS", category_id: 21, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 8, category_name: "TOPPINGS", category_color: "#FBBF24" },
  { id: 214, name: "PLATAN NATURAL", category_id: 21, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 9, category_name: "TOPPINGS", category_color: "#FBBF24" },
  { id: 215, name: "SUCRE", category_id: 21, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 10, category_name: "TOPPINGS", category_color: "#FBBF24" },
  { id: 216, name: "CRUMBLE MADUIXA", category_id: 21, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 11, category_name: "TOPPINGS", category_color: "#FBBF24" },
  { id: 217, name: "CRISPY BALLS NEGRA", category_id: 21, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 12, category_name: "TOPPINGS", category_color: "#FBBF24" },
  { id: 281, name: "KINDER GALLETA", category_id: 21, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 13, category_name: "TOPPINGS", category_color: "#FBBF24" },
  { id: 288, name: "GRANOLA", category_id: 21, price: 0.00, vat_rate: 10, image_url: null, active: true, sort_order: 14, category_name: "TOPPINGS", category_color: "#FBBF24" },

  // ── TOPPING GELAT 1€ (cat 22) — all 1.00€ ──
  { id: 218, name: "GELAT LOTUS", category_id: 22, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "TOPPING GELAT 1\u20AC", category_color: "#60A5FA" },
  { id: 219, name: "GELAT MANGO", category_id: 22, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "TOPPING GELAT 1\u20AC", category_color: "#60A5FA" },
  { id: 220, name: "GELAT A\u00C7AI", category_id: 22, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "TOPPING GELAT 1\u20AC", category_color: "#60A5FA" },
  { id: 221, name: "GELAT VAINILLA", category_id: 22, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "TOPPING GELAT 1\u20AC", category_color: "#60A5FA" },
  { id: 222, name: "GELAT CHEESECAKE", category_id: 22, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "TOPPING GELAT 1\u20AC", category_color: "#60A5FA" },
  { id: 223, name: "GELAT MARACUIA", category_id: 22, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "TOPPING GELAT 1\u20AC", category_color: "#60A5FA" },
  { id: 224, name: "GELAT PISTAXO", category_id: 22, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "TOPPING GELAT 1\u20AC", category_color: "#60A5FA" },
  { id: 225, name: "GELAT NUTELLA", category_id: 22, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 8, category_name: "TOPPING GELAT 1\u20AC", category_color: "#60A5FA" },

  // ── TOPPING 1€ EXTRA (cat 23) — all 1.00€ ──
  { id: 226, name: "NUTELLA 1\u20AC", category_id: 23, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "TOPPING 1\u20AC EXTRA", category_color: "#F472B6" },
  { id: 227, name: "CRISPY BALLS BLANCA 1\u20AC", category_id: 23, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "TOPPING 1\u20AC EXTRA", category_color: "#F472B6" },
  { id: 228, name: "BROWNIE 1\u20AC", category_id: 23, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "TOPPING 1\u20AC EXTRA", category_color: "#F472B6" },
  { id: 229, name: "LACASITOS 1\u20AC", category_id: 23, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "TOPPING 1\u20AC EXTRA", category_color: "#F472B6" },
  { id: 230, name: "LOTUS POLS 1\u20AC", category_id: 23, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "TOPPING 1\u20AC EXTRA", category_color: "#F472B6" },
  { id: 231, name: "MADUIXA NATURAL 1\u20AC", category_id: 23, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "TOPPING 1\u20AC EXTRA", category_color: "#F472B6" },
  { id: 232, name: "NATA 1\u20AC", category_id: 23, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "TOPPING 1\u20AC EXTRA", category_color: "#F472B6" },
  { id: 233, name: "NUBE 1\u20AC", category_id: 23, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 8, category_name: "TOPPING 1\u20AC EXTRA", category_color: "#F472B6" },
  { id: 234, name: "OREO POLS 1\u20AC", category_id: 23, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 9, category_name: "TOPPING 1\u20AC EXTRA", category_color: "#F472B6" },
  { id: 235, name: "PLATAN NATURAL 1\u20AC", category_id: 23, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 10, category_name: "TOPPING 1\u20AC EXTRA", category_color: "#F472B6" },
  { id: 236, name: "SUCRE 1\u20AC", category_id: 23, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 11, category_name: "TOPPING 1\u20AC EXTRA", category_color: "#F472B6" },
  { id: 237, name: "CRISPY BALLS NEGRA 1\u20AC", category_id: 23, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 12, category_name: "TOPPING 1\u20AC EXTRA", category_color: "#F472B6" },
  { id: 238, name: "PISTATXO POLS 1\u20AC", category_id: 23, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 13, category_name: "TOPPING 1\u20AC EXTRA", category_color: "#F472B6" },
  { id: 282, name: "KINDER GALLETA 1\u20AC", category_id: 23, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 14, category_name: "TOPPING 1\u20AC EXTRA", category_color: "#F472B6" },
  { id: 289, name: "GRANOLA 1\u20AC", category_id: 23, price: 1.00, vat_rate: 10, image_url: null, active: true, sort_order: 15, category_name: "TOPPING 1\u20AC EXTRA", category_color: "#F472B6" },

  // ── TOPPING GELAT 2€ (cat 24) — all 2.00€ ──
  { id: 239, name: "GELAT AVELLANA 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 240, name: "GELAT DULCE DE LECHE 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 241, name: "GELAT IOGURT 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 242, name: "GELAT KINDER 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 243, name: "GELAT LOTUS 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 244, name: "GELAT MADUIXA 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 245, name: "GELAT NATA 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 246, name: "GELAT OREO 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 8, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 247, name: "GELAT A\u00C7AI 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 9, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 248, name: "GELAT VAINILLA 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 10, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 249, name: "GELAT XOCOLATA 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 11, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 250, name: "GELAT CAFE 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 12, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 251, name: "GELAT CHEESECAKE 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 13, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 252, name: "GELAT FERRERO 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 14, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 253, name: "GELAT MENTA XOC 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 15, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 254, name: "GELAT PISTAXO 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 16, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 255, name: "GELAT NUTELLA 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 17, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 256, name: "GELAT VAINILLA COOKIES 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 18, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 257, name: "GELAT MARACUIA 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 19, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },
  { id: 258, name: "GELAT CRISPETES 2\u20AC", category_id: 24, price: 2.00, vat_rate: 10, image_url: null, active: true, sort_order: 20, category_name: "TOPPING GELAT 2\u20AC", category_color: "#2DD4BF" },

  // ── TOPPINGS 0,5€ (cat 25) — all 0.50€ ──
  { id: 259, name: "NUTELLA 0,5\u20AC", category_id: 25, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "TOPPINGS 0,5\u20AC", category_color: "#A855F7" },
  { id: 260, name: "CRISPY BALLS BLANCA 0.5\u20AC", category_id: 25, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "TOPPINGS 0,5\u20AC", category_color: "#A855F7" },
  { id: 261, name: "BROWNIE 0.5\u20AC", category_id: 25, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "TOPPINGS 0,5\u20AC", category_color: "#A855F7" },
  { id: 262, name: "LACASITOS 0.5\u20AC", category_id: 25, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "TOPPINGS 0,5\u20AC", category_color: "#A855F7" },
  { id: 263, name: "MADUIXA NATURAL 0.5\u20AC", category_id: 25, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "TOPPINGS 0,5\u20AC", category_color: "#A855F7" },
  { id: 264, name: "NATA 0.5\u20AC", category_id: 25, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "TOPPINGS 0,5\u20AC", category_color: "#A855F7" },
  { id: 265, name: "NUBE 0.5\u20AC", category_id: 25, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "TOPPINGS 0,5\u20AC", category_color: "#A855F7" },
  { id: 266, name: "OREO POLS 0.5\u20AC", category_id: 25, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 8, category_name: "TOPPINGS 0,5\u20AC", category_color: "#A855F7" },
  { id: 267, name: "PLATAN NATURAL 0.5\u20AC", category_id: 25, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 9, category_name: "TOPPINGS 0,5\u20AC", category_color: "#A855F7" },
  { id: 268, name: "SUCRE 0.5\u20AC", category_id: 25, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 10, category_name: "TOPPINGS 0,5\u20AC", category_color: "#A855F7" },
  { id: 269, name: "CRUMBLE MADUIXA 0,5\u20AC", category_id: 25, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 11, category_name: "TOPPINGS 0,5\u20AC", category_color: "#A855F7" },
  { id: 270, name: "CRISPY BALLS NEGRE 0.5\u20AC", category_id: 25, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 12, category_name: "TOPPINGS 0,5\u20AC", category_color: "#A855F7" },
  { id: 283, name: "KINDER GALLETA 0.5\u20AC", category_id: 25, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 13, category_name: "TOPPINGS 0,5\u20AC", category_color: "#A855F7" },
  { id: 290, name: "GRANOLA 0.5\u20AC", category_id: 25, price: 0.50, vat_rate: 10, image_url: null, active: true, sort_order: 14, category_name: "TOPPINGS 0,5\u20AC", category_color: "#A855F7" },

  // ── INFUSIONS (cat 26) ──
  { id: 271, name: "MENTA POLEO", category_id: 26, price: 2.50, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "INFUSIONS", category_color: "#65A30D" },
  { id: 272, name: "ENGLISH BREAKFAST", category_id: 26, price: 2.50, vat_rate: 10, image_url: null, active: true, sort_order: 2, category_name: "INFUSIONS", category_color: "#65A30D" },
  { id: 273, name: "TE VERT", category_id: 26, price: 2.50, vat_rate: 10, image_url: null, active: true, sort_order: 3, category_name: "INFUSIONS", category_color: "#65A30D" },
  { id: 274, name: "CAMAMILLA", category_id: 26, price: 2.50, vat_rate: 10, image_url: null, active: true, sort_order: 4, category_name: "INFUSIONS", category_color: "#65A30D" },
  { id: 275, name: "ROIBOS", category_id: 26, price: 2.50, vat_rate: 10, image_url: null, active: true, sort_order: 5, category_name: "INFUSIONS", category_color: "#65A30D" },
  { id: 276, name: "MENTA POLEO & LLET", category_id: 26, price: 2.70, vat_rate: 10, image_url: null, active: true, sort_order: 6, category_name: "INFUSIONS", category_color: "#65A30D" },
  { id: 277, name: "ENGLISH BREAKFAST & LLET", category_id: 26, price: 2.70, vat_rate: 10, image_url: null, active: true, sort_order: 7, category_name: "INFUSIONS", category_color: "#65A30D" },
  { id: 278, name: "CAMAMILLA & LLET", category_id: 26, price: 2.70, vat_rate: 10, image_url: null, active: true, sort_order: 8, category_name: "INFUSIONS", category_color: "#65A30D" },

  // ── ORXATA (cat 27) ──
  { id: 279, name: "ORXATA", category_id: 27, price: 4.90, vat_rate: 10, image_url: null, active: true, sort_order: 1, category_name: "ORXATA", category_color: "#FCA5A5" },
];
